import Link from "next/link";

export const metadata = { title: "Terms of Service — RECALL" };

const SECTIONS = [
  {
    heading: "1. About these terms",
    body: "RECALL is a personal document intelligence project. These terms are a placeholder written for completeness — they have not been reviewed by a lawyer and are not a substitute for real legal terms. Replace this page before offering the service to anyone other than yourself.",
  },
  {
    heading: "2. Your account",
    body: "You are responsible for keeping your credentials secure. You may sign in with an email and password or with a Google account. You may change your name and password at any time from Settings.",
  },
  {
    heading: "3. Your content",
    body: "Documents you upload remain yours. RECALL stores the original file, extracts its text into searchable chunks, and generates vector embeddings so the content can be retrieved and cited. Deleting a document removes its file, its chunks, and its vectors.",
  },
  {
    heading: "4. Processing and third parties",
    body: "Text extraction, chunking, embedding and reranking all run locally. Chat answers are generated by a third-party language model provider, which means the text of retrieved passages relevant to your question is sent to that provider in order to produce an answer.",
  },
  {
    heading: "5. Availability",
    body: "The service is provided as-is, with no guarantee of uptime, durability, or fitness for any particular purpose. Keep your own copies of anything important.",
  },
  {
    heading: "6. Storage limits",
    body: "Each account has a storage quota. Uploads that would exceed it are rejected. The current quota and your usage are shown in Settings.",
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-16" style={{ background: "#131313" }}>
      <div className="mx-auto" style={{ maxWidth: 720 }}>
        <Link
          href="/login"
          className="text-xs font-semibold uppercase transition-colors hover:text-white"
          style={{ color: "#8e9192", letterSpacing: "0.1em" }}
        >
          ← Back
        </Link>

        <h1
          className="font-semibold text-white mt-6 mb-2"
          style={{ fontSize: 36, letterSpacing: "-0.03em" }}
        >
          Terms of Service
        </h1>
        <p className="text-sm mb-10" style={{ color: "#8e9192" }}>
          Placeholder terms — not legal advice.
        </p>

        <div className="space-y-8">
          {SECTIONS.map((s) => (
            <section key={s.heading}>
              <h2 className="font-medium text-[#e5e2e1] mb-2" style={{ fontSize: 16 }}>
                {s.heading}
              </h2>
              <p className="text-sm" style={{ color: "#c4c7c8", lineHeight: "22px" }}>
                {s.body}
              </p>
            </section>
          ))}
        </div>

        <p className="text-xs mt-12" style={{ color: "#8e9192" }}>
          See also the{" "}
          <Link href="/privacy" className="text-white hover:underline">
            Privacy Policy
          </Link>
          .
        </p>
      </div>
    </main>
  );
}
